### ISSUE TITLE
9.16 P大树洞已有删除PKUhole相关发言的行为

### ISSUE THREAD

**Issue by AowuCat** [pdnywl/what-about-pkuhole#1]
我本人长期运行着一个记录树洞发言的程序，结果如下：
03:43:22 1660115 You are being watched in this socalled anoynomous 树洞. However, we have a new liberal and pure one. 鸿蒙树洞，给你原初的树洞体验 pkuhole.com
该条树洞在07:26:30后的十分钟内被删除。

根据之前的统计数据分析，树洞管理员在凌晨2点后无删帖行为，8点前上班。
想必这条树洞的发帖人对这个规律也有一定了解。

感谢您的分析。

**Comment by pdnywl** [comment]
谢谢关注。我个人也发现了蹊跷，但是正在我更新证据时我发现置顶帖的 #6641848 也被删除了，删除时间大概是凌晨2点至5点之间。

虽然与 pkuhole 无关，但是不知道您是否对评论删帖有跟踪，也许会发现不同的结果。您对凌晨2-8点的分析是部分正确的，但是P大树洞绝对有凌晨班。我的记录系统就在凌晨3-4点被定向反击过，可见至少有一个代码级别权限的操作人员在夜间长期值班。

**Comment by AowuCat** [comment]
不好意思，我没有对评论进行跟踪。
我的记录系统访问频率很低，暂时没有遇到过异常。

我暂时相信PKUhole真的想做一个没有官方管理的树洞。以我个人的价值观来看，删帖记录所呈现的内容是无法接受的。我乐于见到这样一个挑战者。

直到阅读了今天的删帖记录，我才知道PKUhole的存在，但好像改为需要邀请码才能注册了。不知您有没有什么办法？我将不胜感激。

**Comment by pdnywl** [comment]
邀请码自我发现时一直就有，树洞里零零星星能找到一些，亲测 `7050B85429` 还是可用的。

访问频率低就好。我之前在夜间访问频率没有调整，肯定一眼就是异常的流量。效果就是返回的树洞全部为狗屁不通生成器的内容。

无疑 pkuhole.com 是一个不错的尝试，但是如何对抗置顶帖是个大问题。我更新了我的write up，我认为管理者是有一定运营经验的。下一步 pkuhole.com 怎么走将非常有趣。

**Comment by AowuCat** [comment]
十分感谢您！
